version: '3'
services:
  postgres:
    image: 'postgres:12'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  jwt-api:
    image: 'spencer2k23/jwt-api:latest'
    ports:
      - "8080:8080"
    depends_on:
      - postgres